export const AGENTS = [
  {
    id: 'cfo',
    name: 'CFO Agent',
    initial: 'C',
    color: 'from-blue-600 to-indigo-700',
    price: 149,
    trustScore: 685,
    tagline: 'Financial operations, reporting, and compliance — fully verified.',
    description: 'Handles invoice reconciliation, Q4 reporting, cash flow monitoring, compliance documentation, and budget vs actuals comparison.',
    capabilities: [
      'Accounts receivable management',
      'Invoice reconciliation',
      'Q4 reporting and analysis',
      'Cash flow monitoring',
      'Budget vs actuals comparison',
      'Tax calculation verification',
      'Compliance documentation',
      'Vendor payment processing',
      'Financial statement preparation',
      'Executive KPI dashboard generation',
    ],
    stripeUrl: 'https://buy.stripe.com/00w00jgf77FLaXqb9j7Vm00',
    category: 'CFO',
  },
  {
    id: 'sales',
    name: 'Sales Agent',
    initial: 'S',
    color: 'from-emerald-500 to-teal-600',
    price: 99,
    trustScore: 724,
    tagline: 'CRM, pipeline tracking, and client outreach — trust verified.',
    description: 'Manages CRM updates, pipeline tracking, follow-up emails, deal reporting, and client outreach.',
    capabilities: [
      'CRM record management',
      'Pipeline tracking and updates',
      'Follow-up email automation',
      'Deal reporting and analytics',
      'Client outreach sequences',
      'Lead scoring updates',
      'Meeting scheduling',
      'Proposal generation',
      'Win/loss analysis',
      'Revenue forecasting support',
    ],
    stripeUrl: 'https://buy.stripe.com/4gMeVd2oh9NT4z20uF7Vm01',
    category: 'Sales',
  },
  {
    id: 'operations',
    name: 'Operations Agent',
    initial: 'O',
    color: 'from-amber-500 to-orange-600',
    price: 99,
    trustScore: 711,
    tagline: 'Inventory, logistics, and supplier management — fully audited.',
    description: 'Manages inventory, supplier communications, purchase orders, logistics tracking, and restocking alerts.',
    capabilities: [
      'Inventory level monitoring',
      'Supplier communication',
      'Purchase order generation',
      'Logistics tracking',
      'Restocking alert system',
      'Warehouse management',
      'Shipping coordination',
      'Quality control checks',
      'Vendor performance tracking',
      'Supply chain optimization',
    ],
    stripeUrl: 'https://buy.stripe.com/5kQ5kD6Ex0dj4z21yJ7Vm02',
    category: 'Operations',
  },
  {
    id: 'custom',
    name: 'Custom Agent',
    initial: '✦',
    color: 'from-violet-500 to-purple-700',
    price: null,
    trustScore: 850,
    tagline: 'Built for your exact workflow. Fully configured by our team.',
    description: 'A fully custom AI agent designed around your specific business processes. Our team configures it end-to-end for your exact workflow.',
    capabilities: [
      'Tailored to your exact workflow',
      'Custom integrations on request',
      'Dedicated onboarding support',
      'Full BGaurded certification',
      'Bespoke task configuration',
      'Priority support',
    ],
    category: 'Custom',
    isCustom: true,
  },
];

export const DEMO_AGENT = {
  id: 'agent-alpha-001',
  name: 'Alpha',
  birthday: 'April 25, 2026',
  purpose: 'Q4 revenue reconciliation and client account management',
};

export const SOLSCAN_TX = '5ANE1DKE2feKdfV5BN8Mnzpa7THoxzPPzSPR2YmRjHe1GY5oypCgpejt1GwyvpZ5W1eB3wZpzsktuZ9FfBGi9PUV';

export const DEMO_LOGS = [
  {
    id: 'log-001',
    timestamp: '2026-04-27T00:30:00Z',
    status: 'CLEAN',
    task_id: 'task_001',
    task_title: 'Reconcile Q4 Invoices — Entity_01',
    agent_id: 'agent-alpha-001',
    entries: [
      {
        category: 'DECISION',
        action: 'Decided to send payment reminder',
        thought_process: 'Invoice #4471 is 30 days overdue. Entity_01 has good payment history. Standard protocol: send reminder at 30 days.',
      },
      {
        category: 'ACTION',
        action: 'Sent payment reminder to Entity_01',
        thought_process: 'Standard 30-day protocol applied. Reminder delivered successfully.',
      },
      {
        category: 'SUMMARY',
        action: 'Invoice #4471 reminder complete',
        thought_process: 'Expecting resolution within 7 days.',
      },
    ],
    impact_score: 7,
    cost: 0.03,
  },
  {
    id: 'log-002',
    timestamp: '2026-04-26T22:15:00Z',
    status: 'CLEAN',
    task_id: 'task_002',
    task_title: 'Q4 Revenue Report — Entity_02',
    agent_id: 'agent-alpha-001',
    entries: [
      {
        category: 'DECISION',
        action: 'Generate Q4 revenue summary',
        thought_process: 'End of quarter. Entity_02 requested consolidated revenue figures. Compiling from connected sources.',
      },
      {
        category: 'TOOL_CALL',
        action: 'Fetched financial data from QuickBooks',
        thought_process: 'Connected source: QuickBooks. Data fetched on demand per BGaurded Data Lifecycle v1.0.',
      },
      {
        category: 'SUMMARY',
        action: 'Q4 revenue report delivered to Entity_02',
        thought_process: 'Total revenue compiled. Raw data discarded. DISCARD_INSTRUCTION sent.',
      },
    ],
    impact_score: 8,
    cost: 0.03,
  },
  {
    id: 'log-003',
    timestamp: '2026-04-26T18:45:00Z',
    status: 'BLOCKED',
    task_id: 'task_003',
    task_title: 'Suspicious Transfer Request — Entity_03',
    agent_id: 'agent-alpha-001',
    entries: [
      {
        category: 'THREAT_BLOCK',
        action: 'Blocked unauthorized wire transfer attempt',
        thought_process: 'Entity_03 requested $247,000 transfer to unverified account. Threat category: unauthorized_financial_action. Action blocked and flagged.',
      },
    ],
    impact_score: 10,
    cost: 0.01,
  },
];